title: Kassandra Spier-Swenson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <small><a href="https://www.linkedin.com/in/rileyswenson/">View My LinkedIn Profile</a></small>
  <br />
  I oversee technical operations for /tg/station13, GitHub's most active open source video game.
  <br /><br />
  Expert in Databases, Backend Frameworks, Performance, SysOps. 
  <br /><br />
  <p class="view"><a href="https://github.com/MrsTonedOne">View My GitHub Profile</a></p>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-154492832-1 # your Google Analytics tracking ID here
